version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_DB: recipes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
